Homework#2 completed
Wizzard008/VladimirRyzhenkov pull request #2
Opened 2021-06-19 08:46 UTC by Wizzard008

2021-06-22 17:19 UTC, shoggy requested changes

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex2/WebPageTestsCommonConditions.java
> +public class WebPageTestsCommonConditions {
looks like exact copy of `ru.training.at.hw2.ex1.WebPageTestsCommonConditions`
Please fix unnecessary duplication

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .elementToBeClickable(By.id("name"))).sendKeys(LOGIN_NAME);
Linebreaks are hard to read. Compare to the following
```suggestion
        new WebDriverWait(driver, WAIT_TIMEOUT_SECONDS)
            .until(ExpectedConditions.elementToBeClickable(By.id("name")))
            .sendKeys(LOGIN_NAME);
```

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        String expectedUsername = "ROMAN IOVLEV";
Input data (login/password) and expected data is stored in different places, but all of them are "test input data" and should be treated in the same way

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .presenceOfAllElementsLocatedBy(By.xpath("//div[1]/nav[1]/ul[1]/li/a")));
Please improve locator (remember the order: DOM, CSS, XPATH)

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        Assert.assertEquals(headerMenuButtons.get(3).getText(), "METALS & COLORS");
It looks like one assertion

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .presenceOfAllElementsLocatedBy(By.xpath("//div[contains(@class,\"icon\")]")));
Please improve locator (CSS is better choice here)

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        Assert.assertTrue(iconsTextsWebElements.get(3).getText().equalsIgnoreCase(expectedForthBoxText));
Again, looks like one assert

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        Assert.assertTrue(driver.getPageSource().contains("iframe"));
`.getPageSource()` returns a string with Html code, which is not what you really want

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        Assert.assertTrue(driver.getPageSource().contains("frame-button"));
The same
please look into docs or examples, e.g. [this](https://www.guru99.com/handling-iframes-selenium.html)

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +                .presenceOfAllElementsLocatedBy(By.xpath("//ul[@class=\"sidebar-menu left\"]/li/a/span")));
Please use more readable selector

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +    }
This looks like one assert too

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex2/EpamDemoWebPageTests.java
> +            .elementToBeClickable(By.xpath("//li[@class=\"dropdown\"]/*[@class=\"dropdown-toggle\"]"))).click();
Please use CSS equivalent

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex2/EpamDemoWebPageTests.java
> +        ) {
Please use more Javaic breaks :)
```suggestion
        for (WebElement el : checkboxMenuItems) {
```

2021-06-22 17:19 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex2/EpamDemoWebPageTests.java
> +        Assert.assertTrue(driver.getPageSource().contains("Water: condition changed to true"));
replace `.getPageSource()` with other approach

2021-06-23 15:09 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex2/WebPageTestsCommonConditions.java
> +public class WebPageTestsCommonConditions {
WebPageTestsCommonConditions moved to util package.

2021-06-23 15:32 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        String expectedUsername = "ROMAN IOVLEV";
Corrected

2021-06-23 15:43 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .presenceOfAllElementsLocatedBy(By.xpath("//div[1]/nav[1]/ul[1]/li/a")));
Corrected: By.xpath("//*[@class=\"uui-navigation nav navbar-nav m-l8\"]/li")

2021-06-23 15:54 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        Assert.assertEquals(headerMenuButtons.get(3).getText(), "METALS & COLORS");
Corrected.  
        String[] actualHeaderMenuTitles = headerMenuButtons.stream().map(WebElement::getText).toArray(String[]::new);
        String[] expectedHeaderMenuTitles = {"HOME","CONTACT FORM","SERVICE","METALS & COLORS"};
        Assert.assertEquals(actualHeaderMenuTitles,expectedHeaderMenuTitles);

2021-06-23 17:13 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .presenceOfAllElementsLocatedBy(By.xpath("//div[contains(@class,\"icon\")]")));
Changed to By.cssSelector("[class=\"benefit-icon\"]"

2021-06-23 17:14 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        String expectedUsername = "ROMAN IOVLEV";
String userLogin = "Roman";
        String userPassword = "Jdi1234";
        new WebDriverWait(driver, WAIT_TIMEOUT_SECONDS)
            .until(ExpectedConditions.elementToBeClickable(By.id("name")))
            .sendKeys(userLogin);

        new WebDriverWait(driver, WAIT_TIMEOUT_SECONDS)
            .until(ExpectedConditions.elementToBeClickable(By.id("password")))
            .sendKeys(userPassword);

2021-06-23 17:19 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .presenceOfAllElementsLocatedBy(By.xpath("//div[1]/nav[1]/ul[1]/li/a")));
Corrected
By.cssSelector("[class=\"uui-navigation nav navbar-nav m-l8\"] > li"

2021-06-23 17:25 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        Assert.assertTrue(iconsTextsWebElements.get(3).getText().equalsIgnoreCase(expectedForthBoxText));
Corrected
        String[] actualIconsTexts = iconsTextsWebElements.stream().map(WebElement::getText).toArray(String[]::new);
        String[] expectedIconsTexts = {expectedFirstBoxText,expectedSecondBoxText,expectedThirdBoxText,expectedForthBoxText};
        Assert.assertEquals(actualIconsTexts,expectedIconsTexts);

2021-06-23 17:26 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex2/EpamDemoWebPageTests.java
> +        ) {
Corrected

2021-06-23 17:29 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        Assert.assertTrue(driver.getPageSource().contains("iframe"));
Corrected
        WebElement iframe = new WebDriverWait(driver, WAIT_TIMEOUT_SECONDS)
            .until(ExpectedConditions.presenceOfElementLocated(By.id("frame")));
        Assert.assertTrue(iframe.isDisplayed());

2021-06-23 17:33 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +        Assert.assertTrue(driver.getPageSource().contains("frame-button"));
Corrected
        WebElement frameButtonWebElement = new WebDriverWait(driver, WAIT_TIMEOUT_SECONDS)
            .until(ExpectedConditions.presenceOfElementLocated(By.id("frame-button")));

        Assert.assertTrue(frameButtonWebElement.isDisplayed());

2021-06-23 17:39 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +                .presenceOfAllElementsLocatedBy(By.xpath("//ul[@class=\"sidebar-menu left\"]/li/a/span")));
Changed
By.cssSelector("#mCSB_1_container > ul > li > a > span"

2021-06-23 17:42 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +    }
Corrected
        String[] actualMenuItemsTexts =
            leftSectionMenuWebElements.stream().map(WebElement::getText).toArray(String[]::new);
        String[] expectedMenuItemsTexts = {"Home", "Contact form", "Service", "Metals & Colors", "Elements packs"};
        Assert.assertEquals(actualMenuItemsTexts, expectedMenuItemsTexts);

2021-06-23 17:50 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex2/EpamDemoWebPageTests.java
> +            .elementToBeClickable(By.xpath("//li[@class=\"dropdown\"]/*[@class=\"dropdown-toggle\"]"))).click();
Changed into
By.cssSelector("[class=\"dropdown-toggle\"]")

2021-06-23 18:03 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex2/EpamDemoWebPageTests.java
> +        Assert.assertTrue(driver.getPageSource().contains("Water: condition changed to true"));
Corrected with softAssert
        String[] actualLogItemsTexts = webpageLogItems.stream().map(WebElement::getText).toArray(String[]::new);
        String[] expectedPartialLogItemsTexts =
            {"Colors: value changed to Yellow", "metal: value changed to  Selen", "Wind: condition changed to true",
                "Water: condition changed to true"};

        SoftAssert softAssert = new SoftAssert();
        softAssert.assertEquals(actualLogItemsTexts,expectedPartialLogItemsTexts);

2021-06-23 18:03 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .elementToBeClickable(By.id("name"))).sendKeys(LOGIN_NAME);
Corrected

2021-06-24 20:00 UTC, shoggy requested changes

2021-06-24 20:00 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.cssSelector("[class=\"benefit-icon\"]")));
```suggestion
            .until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.cssSelector(".benefit-icon")));
```

2021-06-24 20:00 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .until(ExpectedConditions.presenceOfElementLocated(By.id("frame-button")));
Somewhere here you need to switch into iframe

2021-06-25 05:11 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw2/ex1/EpamDemoWebPageTests.java
> +            .until(ExpectedConditions.presenceOfElementLocated(By.id("frame-button")));
Corrected

2021-06-25 23:10 UTC, shoggy approved these changes

2021-06-26 05:57 UTC, merged