Homework#3 - completed
Wizzard008/VladimirRyzhenkov pull request #5
Opened 2021-06-27 16:27 UTC by Wizzard008

2021-06-29 15:37 UTC, shoggy reviewed
Tests cannot be run
```
java.lang.ExceptionInInitializerError
	at ru.training.at.hw3.util.WebPageTestsCommonConditions.<init>(WebPageTestsCommonConditions.java:15)
```

2021-06-29 15:37 UTC, shoggy commented on src/test/java/ru/training/at/hw3/page/component/EventLogComponent.java
> +    @FindBy(css = "[class=\"panel-body-list logs\"] > li")
Please rewrite in more readable form

2021-06-29 15:37 UTC, shoggy commented on pom.xml
> +        <testSuiteXmlFile>${testng.configs.path}/HW3EX2.xml</testSuiteXmlFile>
Add default activation please

2021-06-29 15:37 UTC, shoggy commented on src/test/java/ru/training/at/hw3/ex1/WebPageTestDataProviderEx1.java
> +            {"Home Page", "ROMAN IOVLEV", 4, HEADER_MENU_TITLES, INDEX_PAGE_ICONS_TEXTS, LEFT_SECTION_MENU_TITLES}
At least second argument is a good candidate for externalization (like login/password)

2021-06-29 15:37 UTC, shoggy commented on src/test/java/ru/training/at/hw3/page/component/ColorSelectorComponent.java
> +    @FindBy(xpath = "//option[text()=\"Yellow\"]")
You can use `'`' instead of `"` in selectors. Fewer escape symbols -- easier to read

2021-06-29 15:37 UTC, shoggy commented on src/test/java/ru/training/at/hw3/page/component/FrameComponent.java
> +        return iframe.isDisplayed();
If the frame is not present then `org.openqa.selenium.NoSuchElementException` will be thrown, in this case, test receive a Broken state instead of a Failed

2021-06-29 15:37 UTC, shoggy commented on src/test/java/ru/training/at/hw3/page/component/IconsComponent.java
> +    @FindBy(xpath = "//span[contains(@class,\"benefit-txt\")]")
Use CSS please

2021-06-29 15:37 UTC, shoggy commented on pom.xml
> +    </profile>
Please merge these two profiles into one

2021-06-29 15:38 UTC, shoggy requested changes
.

2021-06-30 05:53 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw3/page/component/EventLogComponent.java
> +    @FindBy(css = "[class=\"panel-body-list logs\"] > li")
css = "div.info-panel-section > ul > li"

2021-06-30 05:55 UTC, Wizzard008 commented on pom.xml
> +        <testSuiteXmlFile>${testng.configs.path}/HW3EX2.xml</testSuiteXmlFile>
<activation>
        <activeByDefault>true</activeByDefault>
      </activation>

2021-06-30 05:56 UTC, Wizzard008 commented on pom.xml
> +    </profile>
<profile>
      <id>Homework#3-AllTestsSuite</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <testSuiteXmlFile>${testng.configs.path}/HW3.xml</testSuiteXmlFile>
      </properties>
    </profile>

2021-06-30 06:08 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw3/ex1/WebPageTestDataProviderEx1.java
> +            {"Home Page", "ROMAN IOVLEV", 4, HEADER_MENU_TITLES, INDEX_PAGE_ICONS_TEXTS, LEFT_SECTION_MENU_TITLES}
Done

2021-06-30 06:13 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw3/page/component/ColorSelectorComponent.java
> +    @FindBy(xpath = "//option[text()=\"Yellow\"]")
Corrected

2021-06-30 06:17 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw3/page/component/IconsComponent.java
> +    @FindBy(xpath = "//span[contains(@class,\"benefit-txt\")]")
@FindBy(css = "[class^='benefit-txt']")

2021-06-30 06:34 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw3/page/component/FrameComponent.java
> +        return iframe.isDisplayed();
try {
            Assert.assertTrue(webPageObject.getIframe().isDisplayed());
        } catch (NullPointerException e) {
            Assert.fail();
        } catch (Exception e) {
            e.printStackTrace();
        }

2021-06-30 08:40 UTC, shoggy approved these changes

2021-06-30 08:40 UTC, shoggy commented on src/test/java/ru/training/at/hw3/page/component/IconsComponent.java
> +    @FindBy(css = "[class^='benefit-txt']")
```suggestion
    @FindBy(css = ".benefit-txt")
```

2021-06-30 08:40 UTC, shoggy commented on src/test/java/ru/training/at/hw3/page/component/HeaderComponent.java
> +    @FindBy(css = "[class='uui-navigation nav navbar-nav m-l8'] > li")
```suggestion
    @FindBy(css = ".uui-navigation.nav.navbar-nav.m-l8 > li")
```

2021-06-30 11:31 UTC, merged