Homework#7/8 - completed
Wizzard008/VladimirRyzhenkov pull request #9
Opened 2021-07-11 16:13 UTC by Wizzard008

2021-07-14 21:20 UTC, pnatashap requested changes
замечание про путь исправлять не обязательно, остальное надо бы поправить, чтобы красивый пример был

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/GdiWebSite.java
> +public class GdiWebSite {
Jdi :)

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/TestsInit.java
> +        killAllSeleniumDrivers();
убивать браузер в начале сьюта при параллельном запуске тестов в какой-то момент выстрелит в ногу: сьюты будут рандомно падать при запуске нового. надо будет выпилить из примера.
но это пример бездумного copy-paste :)

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/states/TestStates.java
> +    public static void assertion(String expectedResult) {
не очень метод называется.... без заглядывания в исходник не понятно, что делает - значит не очень название

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/states/TestStates.java
> +    public static void submit() {
очень странный метод. со временем кодовая база увеличится и станет не понятно, что оно сабмитит

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/states/TestStates.java
> +    public static void selectElement(String[] elementsToSelect) {
тоже не очень название, элемент - достаточно общее слово, а никак не понять, что оно к конкретной странице только относится

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/tests/TestDataProvider.java
> +                break;
не очень хорошая идея выходить при любой ошибке, нужно выходить только если объекта нет.
допустим в первой же строке измени где-то число на строку, вылетет исключение, но это не значит, что дальше читать не надо.

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/tests/TestDataProvider.java
> +        FileReader reader = new FileReader("src/test/resources/JDI_ex8_metalsColorsDataSet.json");
предположим ситуацию: я собираю jar, закидываю его в спец среду, где проводятся прогоны. как думаешь, сильно лениво мне будет такой путь создавать? 
это частая ситуация в жизни, когда артифакт собирается один раз, потом много раз гоняется с разными настройками.

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/tests/WebPageTest.java
> +        login();
Step делается для того, чтобы документация была там

2021-07-14 21:20 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/tests/WebPageTest.java
> +    public void webPageTests(TestData testData) {
название теста малопонятно, не хорошо так

2021-07-16 06:22 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw7/GdiWebSite.java
> +public class GdiWebSite {
Поправил :)

2021-07-16 06:22 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw7/TestsInit.java
> +        killAllSeleniumDrivers();
Убрал

2021-07-16 06:23 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw7/states/TestStates.java
> +    public static void assertion(String expectedResult) {
Поправил

2021-07-16 06:25 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw7/states/TestStates.java
> +    public static void submit() {
Поправил

2021-07-16 06:28 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw7/states/TestStates.java
> +    public static void selectElement(String[] elementsToSelect) {
Поправил

2021-07-16 06:33 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw7/tests/TestDataProvider.java
> +                break;
Поправил

2021-07-16 06:36 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw7/tests/WebPageTest.java
> +    public void webPageTests(TestData testData) {
Поправил

2021-07-16 06:54 UTC, Wizzard008 commented on src/test/java/ru/training/at/hw7/tests/TestDataProvider.java
> +        FileReader reader = new FileReader("src/test/resources/JDI_ex8_metalsColorsDataSet.json");
Добавил qa.properties для указания с файла с данными.

2021-07-20 20:03 UTC, pnatashap approved these changes

2021-07-20 20:03 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/tests/TestDataProvider.java
> +        String dataFilePath = RESOURCE_ROOT_FOLDER + resourceBundle.getString(METALS_AND_COLORS_DATA);
изменение без особого смысла: все равно из src чтение происходит, не важно в константе она или нет. все равно в реальности стараются оттуда не читать

2021-07-20 20:03 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/tests/TestDataProvider.java
> +                break;
не самое удачное исправление, но уже лучше

2021-07-20 21:20 UTC, merged